version: "3.8"

services:
  app:
    image: myapp:latest
    container_name: app_container
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb
    volumes:
      - app_data:/app/data
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: db_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  proxy:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app_network

volumes:
  app_data:
  db_data:

networks:
  app_network:
    driver: bridge
